const startups: Startup[] = [
    { id: 1, name: 'Tech Innovators', industry: 'Technology', status: 'Ready to launch in Market', region: 'North America', price: 50000000 },
    { id: 2, name: 'HealthFirst', industry: 'Healthcare', status: 'Under Development', region: 'Asia', price: 20000000 },
    { id: 3, name: 'EduSpark', industry: 'Education', status: 'Developed', region: 'Europe', price: 10000000 },
    { id: 4, name: 'E-Mart', industry: 'E-commerce', status: 'Ready to launch in Market', region: 'North America', price: 80000000 },
    { id: 5, name: 'FinServe', industry: 'Finance', status: 'Raw Idea', region: 'Africa', price: 30000000 },
    { id: 6, name: 'GreenTech Solutions', industry: 'Technology', status: 'Developed', region: 'Europe', price: 60000000 },
    { id: 7, name: 'FoodFusion', industry: 'Food & Beverage', status: 'Under Development', region: 'Asia', price: 40000000 },
    { id: 8, name: 'Meditech Pro', industry: 'Healthcare', status: 'Ready to launch in Market', region: 'North America', price: 90000000 },
    { id: 9, name: 'SmartEd', industry: 'Education', status: 'Raw Idea', region: 'Africa', price: 5000000 },
    { id: 10, name: 'StyleSphere', industry: 'Fashion', status: 'Under Development', region: 'Europe', price: 15000000 },
    { id: 11, name: 'AutoPilot', industry: 'Automotive', status: 'Ready to launch in Market', region: 'North America', price: 120000000 },
    { id: 12, name: 'AgriTech Hub', industry: 'Agriculture', status: 'Developed', region: 'Asia', price: 25000000 },
    { id: 13, name: 'FinGrowth', industry: 'Finance', status: 'Under Development', region: 'Europe', price: 40000000 },
    { id: 14, name: 'BioGenics', industry: 'Healthcare', status: 'Raw Idea', region: 'North America', price: 10000000 },
    { id: 15, name: 'EcoHome', industry: 'Real Estate', status: 'Developed', region: 'Asia', price: 70000000 },
    { id: 16, name: 'ShopEase', industry: 'E-commerce', status: 'Ready to launch in Market', region: 'Europe', price: 45000000 },
    { id: 17, name: 'Eventify', industry: 'Event Management', status: 'Under Development', region: 'Africa', price: 20000000 },
    { id: 18, name: 'RideSmart', industry: 'Automotive', status: 'Raw Idea', region: 'Asia', price: 15000000 },
    { id: 19, name: 'GameOn', industry: 'Gaming', status: 'Developed', region: 'North America', price: 60000000 },
    { id: 20, name: 'PetCare', industry: 'Pets', status: 'Ready to launch in Market', region: 'Europe', price: 25000000 },
    { id: 21, name: 'TravelBuddy', industry: 'Travel', status: 'Under Development', region: 'Asia', price: 30000000 },
    { id: 22, name: 'Artify', industry: 'Art & Design', status: 'Raw Idea', region: 'Africa', price: 8000000 },
    { id: 23, name: 'SolarGen', industry: 'Renewable Energy', status: 'Developed', region: 'North America', price: 90000000 },
    { id: 24, name: 'DigitalDocs', industry: 'Healthcare', status: 'Ready to launch in Market', region: 'Asia', price: 50000000 },
    { id: 25, name: 'LearnNest', industry: 'Education', status: 'Under Development', region: 'Europe', price: 20000000 },
    { id: 26, name: 'GadgetPro', industry: 'Technology', status: 'Raw Idea', region: 'Africa', price: 10000000 },
    { id: 27, name: 'BuildSmart', industry: 'Construction', status: 'Developed', region: 'Asia', price: 75000000 },
    { id: 28, name: 'FitPulse', industry: 'Fitness', status: 'Under Development', region: 'North America', price: 40000000 },
    { id: 29, name: 'CleanWave', industry: 'Environment', status: 'Ready to launch in Market', region: 'Europe', price: 55000000 },
    { id: 30, name: 'PlantPure', industry: 'Agriculture', status: 'Raw Idea', region: 'Africa', price: 15000000 },
  ];