name = "inqube-hack-rev"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "20.0.0"
NEXT_PUBLIC_SUPABASE_URL="https://pwbdpoqjytydzskgrbqu.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3YmRwb3FqeXR5ZHpza2dyYnF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMzA4MDQsImV4cCI6MjA1NTcwNjgwNH0.iKr2ViJy49yWdKejNa4IekcSmcMdCZzBqbslgSlm2sE"
