name = "inqube-hack-rev"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_VERSION = "20.0.0"
NEXT_PUBLIC_SUPABASE_URL=https://jlxsdkxjpqhuchzjiudv.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpseHNka3hqcHFodWNoemppdWR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyMDQxNDAsImV4cCI6MjA1MDc4MDE0MH0.dDuPROnQLnhj1f1ElzPThUB1_09wZkP0qxJPKFNnoBA
