import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Importing the Poppins font
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Specify weights based on your requirements
  variable: "--font-poppins", // Define a custom CSS variable for the font
});

export const metadata: Metadata = {
  title: "Inqube | Where Ideas Meet Investors",
  description: "Generated by create next app",
  icons: "https://img.icons8.com/?size=100&id=ezDTR0SCQIf2&format=png&color=000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
