const steps = [
    { title: "Choose Your Startup Idea", description: "Pick an innovative idea.", options: ["AI-powered healthcare assistant", "Sustainable e-commerce platform", "Blockchain for supply chain", "Virtual reality fitness app"] },
    { title: "Select Your Industry", description: "Which industry does your idea target?", options: ["Healthcare", "E-commerce", "Technology", "Education"] },
    { title: "Pick a Business Model", description: "Choose how your startup generates revenue.", options: ["Subscription-based", "Freemium model", "Ad revenue", "One-time payment"] },
    { title: "Choose Your Funding Source", description: "How will you secure initial funding?", options: ["Bootstrapping", "Angel investors", "Crowdfunding", "Venture Capital"] },
    { title: "Select a Marketing Strategy", description: "How will you attract customers?", options: ["Social media campaigns", "Influencer partnerships", "Content marketing", "Traditional advertising"] },
    { title: "Pick a Target Audience", description: "Who is your primary target?", options: ["Young professionals", "Tech-savvy teens", "Small businesses", "Senior citizens"] },
    { title: "Choose Your MVP", description: "What will your Minimum Viable Product (MVP) include?", options: ["Core features", "All features", "Beta testing", "Prototype"] },
    { title: "Plan Your Office Setup", description: "Where will your startup operate?", options: ["Home office", "Co-working space", "Dedicated office", "Remote team"] },
    { title: "Select a Launch Region", description: "Where will you launch first?", options: ["Local market", "National market", "Global market", "Online-only"] },
    { title: "Pick a Tech Stack", description: "What technologies will you use?", options: ["React + Node.js", "Python + Django", "Ruby on Rails", "Java + Spring Boot"] },
    { title: "Build a Team", description: "Who is your first hire?", options: ["Tech-focused CTO", "Marketing wizard", "Experienced designer", "Finance strategist"] },
    { title: "Decide Branding Style", description: "What is your branding style?", options: ["Minimalist", "Bold & Vibrant", "Playful & Fun", "Professional & Clean"] },
    { title: "Choose Customer Support", description: "How will you assist customers?", options: ["Live chat", "Email support", "AI-driven chatbot", "Call center"] },
    { title: "Create a Tagline", description: "What describes your brand best?", options: ["Innovate your future", "Sustainability made easy", "Empower your vision", "Think different"] },
    { title: "Select Scaling Strategy", description: "How will you scale operations?", options: ["Expand to new markets", "Invest in automation", "Hire aggressively", "Develop partnerships"] },
    { title: "Choose Security Features", description: "How secure will your app be?", options: ["Basic encryption", "Multi-factor authentication", "Biometric login", "Full compliance with GDPR"] },
    { title: "Pick a Collaboration Tool", description: "What will your team use?", options: ["Slack", "Microsoft Teams", "Asana", "Trello"] },
    { title: "Set Pricing", description: "How will you price your product?", options: ["Affordable", "Premium", "Freemium", "Custom pricing"] },
    { title: "Launch Strategy", description: "How will you announce your launch?", options: ["Press release", "Product Hunt", "Influencer marketing", "Beta testers"] },
    { title: "Sustain Growth", description: "What will you focus on post-launch?", options: ["Customer retention", "Rapid expansion", "Innovating features", "Building partnerships"] },
  ];